### ISSUE TITLE
Certain Kanji searches return null hiragana sections.

### ISSUE THREAD

**Issue by Eddy-Rogers** [Eddy-Rogers/JishoCSVExtension#7]
For example: 女将 -> 女将, [null] 1. proprietress (of a traditional Japanese inn or restaurant); landlady; hostess; mistress​

**Comment by JosephBrooksbank** [comment]
Now outputs: `女将, [おかみ] proprietress (of a traditional Japanese inn or restaurant); landlady; hostess; mistress`

Fixed in e9c0984f7ab2a2d08614815e8fb0c0d7479bf12f
